fix: Fix SeaBIOS build

diff --git a/build b/build
--- a/build
+++ b/build
@@ -309,16 +309,22 @@ for p in "${platforms[@]}"; do
 
         "$seabios_tool_bin" generate-v86 "$v86_tmp_dir/v86"
         make -C "$v86_tmp_dir/v86" build/v86.wasm
-        make -C "$v86_tmp_dir/seabios" PYTHON="$seabios_tool_bin"
+        make -C "$v86_tmp_dir/seabios" PYTHON="$seabios_tool_bin" out/bios.bin out/vgabios.bin
 
         mkdir -p built/v86_out/build
         mkdir -p built/v86_out/bios
         cp "$v86_tmp_dir/v86/build/v86.wasm" built/v86_out/build/
         if [[ -f "$v86_tmp_dir/seabios/out/bios.bin" ]]; then
             cp "$v86_tmp_dir/seabios/out/bios.bin" built/v86_out/bios/seabios.bin
+        else
+            echo "Could not find built SeaBIOS!"
+            exit 1
         fi
         if [[ -f "$v86_tmp_dir/seabios/out/vgabios.bin" ]]; then
             cp "$v86_tmp_dir/seabios/out/vgabios.bin" built/v86_out/bios/vgabios.bin
+        else
+            echo "Could not find built VGA BIOS!"
+            exit 1
         fi
 
         rm -rf "${v86_tmp_dir?}"
