ci: Try adding a CI configuration

diff --git a/scripts/ci-build-inner b/scripts/ci-build-inner
--- a/scripts/ci-build-inner
+++ b/scripts/ci-build-inner
@@ -19,6 +19,12 @@ if [[ $# -gt 0 ]]; then
 fi
 
 echo "Installing system dependencies..."
+
+npx playwright uninstall-deps chromium \
+    && npx playwright uninstall chromium \
+    && npm uninstall -g typescript playwright || true
+
+# install node and npm so the uninstall can fail if they are present and don't get installed
 apt-get update && apt-get install -y \
     curl \
     git \
@@ -31,7 +37,11 @@ apt-get update && apt-get install -y \
     pkg-config \
     ca-certificates \
     file \
-    xz-utils
+    xz-utils \
+    node \
+    npm
+
+apt-get uninstall -y node npm
 
 if ! command -v guix >/dev/null 2>&1; then
     echo "Installing GNU Guix..."
