fix: Formatting script improvements

diff --git a/scripts/format b/scripts/format
--- a/scripts/format
+++ b/scripts/format
@@ -5,11 +5,11 @@ set -euxo pipefail
 commit() {
     pushd ~/ctoolbox/vendor || exit 1
     git add . || true
-    git commit -m format || true
+    git commit -m 'style: Format automatically' || true
     popd || exit 1
     pushd ~/ctoolbox || exit 1
     git add . || true
-    git commit -m format || true
+    git commit -m 'style: Format automatically' || true
     popd || exit 1
 }
 
@@ -18,7 +18,7 @@ if [[ "${1-}" == "--quick" ]]; then
     quick=true
 fi
 
-trap 'echo "ERROR: Aborting"; pushd ~/ctoolbox; git checkout origin/main -- vendor; git commit -m "Revert vendor directory changes";' EXIT;
+trap 'echo "ERROR: Aborting"; pushd ~/ctoolbox; git checkout origin/main -- vendor; git commit -m "deps: Revert vendor directory changes";' EXIT;
 pushd ~/ctoolbox || exit 1
 
 if [[ "$quick" == false ]]; then
@@ -40,6 +40,6 @@ cargo fmt --all ||  { echo "ERROR: cargo fmt --all failed"; exit 1; }
 commit
 
 git checkout origin/main -- vendor
-git commit -m "Revert vendor directory changes"
+git commit -m "deps: Revert vendor directory changes"
 popd
 trap - EXIT
