refactor: Try to make linter faster.
Not sure if this will break things (why didn't I add more context in that comment?)

diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -18,10 +18,16 @@ while [[ $# -gt 0 ]]; do
     shift
 done
 
-# Documentation needs to exist to build linter (it's fine if it's not up to date, but does need to be there).
-if [[ ! -f target/x86_64-unknown-linux-musl/doc/index.html ]] || [[ ! -f target/x86_64-unknown-linux-musl/doc/help.html ]]; then
-    echo "Docs not found. Building..."
-    cargo doc --workspace --no-deps --target=x86_64-unknown-linux-musl || exit 1
+if [[ -n "$quick" ]]; then
+    export CTB_SKIP_DOCS=1
+fi
+
+if [[ -z "${CTB_SKIP_DOCS:-}" ]]; then
+    # Documentation needs to exist to build linter (it's fine if it's not up to date, but does need to be there).
+    if [[ ! -f target/x86_64-unknown-linux-musl/doc/index.html ]] || [[ ! -f target/x86_64-unknown-linux-musl/doc/help.html ]]; then
+        echo "Docs not found. Building..."
+        cargo doc --workspace --no-deps --target=x86_64-unknown-linux-musl || exit 1
+    fi
 fi
 
 pushd assets || exit 1
